### ISSUE TITLE
Add bear as a dependency

### ISSUE THREAD

**Issue by mority** [tudasc/PIRA#1]
Users who do not use `cmake` in their project need a way to create a compilation database.
This can be achieved using `bear` (https://github.com/rizsotto/Bear).
Therefore, it might be wise to add `bear` as a submodule to install with `pira`.
Code for installing `bear` can already be found in `pira/test/integration/prepare_environment.sh`.

**Comment by jplehr** [comment]
That is a valid point.

We'll add it at the latest with the next release as a dependency.

**Comment by jplehr** [comment]
This has been addressed by now in our internal Gitlab, and will shortly be published here.
